### ISSUE TITLE
No uninstall option

### ISSUE THREAD

**Issue by ashquarky** [PretendoNetwork/Martini#1]
As said on the tin, Martini does not have an option to undo its patches right now. Users have to manually restore the backup files martini makes or reinstall the titles entirely. We should document the manual uninstall process, and add automatic uninstall functionality to Martini.

**Comment by MythicalPlayz** [comment]
Quick question where does the backup save ?

**Comment by ashquarky** [comment]
Each file is backed up by copying it and adding `.orig` to the end of its name, see the paths here: https://github.com/PretendoNetwork/Martini/blob/953b70e2581bd5381660c4ba521e5ea72da777f8/main.cpp#L104-L114

I wouldn't suggest restoring these by hand, WUPInstalling the titles involved is a bit more foolproof.

**Comment by homebrewGT** [comment]
Any idea when the Uninstaller will be available?

**Comment by MythicalPlayz** [comment]
there should be an uninstall option now.

**Comment by TheGhostboi64** [comment]
> there should be an uninstall option now.

Really? because I need to uninstall martini because aroma will keep getting error 102-2402 when trying to connect to online services

**Comment by MythicalPlayz** [comment]
@TheGhostboi64  Cause Juxt is offline right now

**Comment by TheGhostboi64** [comment]
oh

**Comment by frruu** [comment]
> there should be an uninstall option now.

there isn't tho (sorry for accidentally opening a new issue 💀)

**Comment by ninstar** [comment]
If anyone ever build a official release with the uninstaller I would suggest implementing a second backup directly to the SD card just in case.

Also, I think this should be clarified somewhere in the readme:

> Each file is backed up by copying it and adding `.orig` to the end of its name, see the paths here:
> 
> https://github.com/PretendoNetwork/Martini/blob/953b70e2581bd5381660c4ba521e5ea72da777f8/main.cpp#L104-L114
> 
> I wouldn't suggest restoring these by hand, WUPInstalling the titles involved is a bit more foolproof.
