### ISSUE TITLE
Error 678-1008 

### ISSUE THREAD

**Issue by falin24** [PretendoNetwork/Martini#11]
Hi, I try to use  Martini Patcher to use miiverese but I got error 678-1008 I don´t know why this error if one got the same or know a solution please let a comment bye

**Comment by falin24** [comment]
Note: I use Aroma

**Comment by ashquarky** [comment]
Martini isn't recommended for Aroma users (or anyone) anymore - if you check the [setup instructions on our website](https://pretendo.network/docs/install/wiiu) you'll see info on setting up our new patcher, Inkay, for Aroma.

Where did you see mention of Martini? We might have to update that info.

**Comment by falin24** [comment]
But I try with Tiramisu and same error

**Comment by falin24** [comment]
And what I need to do to use Miiverse in aroma?

**Comment by ashquarky** [comment]
The current version of Inkay (v2.2.x) will do the Miiverse patching, you should be fine using that on Aroma. We do *not* support Tiramisu and we no longer support Martini.

Closing as WONTFIX.

**Comment by falin24** [comment]
Thank you so much!

**Comment by falin24** [comment]
:)
