### ISSUE TITLE
there should be an uninstall option now.

### ISSUE THREAD

**Issue by frruu** [PretendoNetwork/Martini#9]
there should be an uninstall option now.

_Originally posted by @MythicalPlayz in https://github.com/PretendoNetwork/Martini/issues/1#issuecomment-1256914652_
            
            there isn't tho

**Comment by MythicalPlayz** [comment]
there is tho you may need to build it from source or your backup is curropted

**Comment by frruu** [comment]
i've tried building from the source and it's literal hell, my backup isnt corrupted im pretty sure
